---
title: "Log Scale"
author: "Camden Blatchly"
date: "5/26/2021"
output: html_document
---

```{r setup, include=FALSE, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r, include=FALSE, echo=FALSE}
source("setup.R")
library(knitr)
library(patchwork)

indicators_12 <- indicators_2012$indicator %>% unique()
subpops_12 <- indicators_2012$subpopulation %>% unique()

indicators_17 <- indicators_2017$indicator %>% unique()
subpops_17 <- indicators_2017$subpopulation %>% unique()

```


```{r fig.height=1, fig.width=10, results='asis', echo=FALSE}

for (indi in indicators_12) {
  for (subpop in region_lookup_table$state_abbr) {
    
    epa_region <-
      region_lookup_table %>%
      filter(state_abbr == subpop) %>%
      pull(epa_region)

    subpop_max <- indicators %>%
      filter(indicator == indi) %>%
      filter(subpopulation == subpop) %>%
      filter(statistic == "95Pct") %>%
      pull(estimate) %>% 
      max()
    
    region_max <- indicators %>%
      filter(indicator == indi) %>%
      filter(subpopulation == epa_region) %>%
      filter(statistic == "95Pct") %>%
      pull(estimate) %>% 
      max()
    
    allsites_max <- indicators %>%
      filter(indicator == indi) %>%
      filter(subpopulation == "All_Sites") %>%
      filter(statistic == "95Pct") %>%
      pull(estimate) %>% 
      max()
    
    across_plot_max <- max(subpop_max, region_max, allsites_max)
    
    p1 <- indicator_plot(indicators_2012, subpop, indi, measurements[indi][[1]], across_plot_max) + theme(plot.margin = unit(c(0,20,0,20), "pt"))
    p2 <- indicator_plot(indicators_2017, subpop, indi, measurements[indi][[1]], across_plot_max) + theme(plot.margin = unit(c(0,20,0,20), "pt"))

    p3 <- indicator_plot(indicators_2012, epa_region, indi, measurements[indi][[1]], across_plot_max) + theme(plot.margin = unit(c(0,20,0,20), "pt"))
    p4 <- indicator_plot(indicators_2017, epa_region, indi, measurements[indi][[1]], across_plot_max) + theme(plot.margin = unit(c(0,20,0,20), "pt"))

    p5 <- indicator_plot(indicators_2012, "All_Sites", indi, measurements[indi][[1]], across_plot_max) + theme(plot.margin = unit(c(0,20,0,20), "pt"))
    p6 <- indicator_plot(indicators_2017, "All_Sites", indi, measurements[indi][[1]], across_plot_max) + theme(plot.margin = unit(c(0,20,0,20), "pt"))

    cat("\n##### Indicator: ", indi, " Subpop: ", subpop, " (2012 compared to 2017)\n")
    print(p1 | p2)
    cat("\n ", epa_region, "\n")
    print(p3 | p4)
    cat("\n All Sites\n")
    print(p5 | p6)
    
    cat("  \n")
  }
}

```
