---
title: "Scale Version 2"
output: html_document
---

```{r setup, include=FALSE, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r, include=FALSE, echo=FALSE}
source("setup.R")
library(knitr)
library(patchwork)
library(dplyr)

indicators_12 <- indicators_2012$indicator %>% unique()
subpops_12 <- indicators_2012$subpopulation %>% unique()

indicators_17 <- indicators_2017$indicator %>% unique()
subpops_17 <- indicators_2017$subpopulation %>% unique()

```


```{r fig.height=1, fig.width=15, results='asis', echo=FALSE}

for (indi in indicators_12) {
  for (subpop in subpops_12) {
    
    df <- indicators_2012 %>% 
      dplyr::filter(subpopulation == subpop,
           indicator == indi,
           statistic %in% bp_stats)
  
    y5 <- getStat(df, "5Pct", 10000000000000)
    y95 <- getStat(df, "95Pct", 10000000000000)
    
    cat("\n###### ", indi, " | ", subpop, " | 2012 (",y5, ", ", y95, ") \n")
    p1 <- indicator_plot(indicators_2012, subpop, indi, measurements[indi][[1]], scale_max[indi][[1]])# + theme(plot.margin = unit(c(0,10,0,10), "pt"))
    print(p1)
    cat("  \n")
    
    df <- indicators_2017 %>% 
      dplyr::filter(subpopulation == subpop,
           indicator == indi,
           statistic %in% bp_stats)
  
    y5 <- getStat(df, "5Pct", 10000000000000)
    y95 <- getStat(df, "95Pct", 10000000000000)
    
    cat("\n###### ", indi, " | ", subpop, " | 2017 (",y5, ", ", y95, ") \n")
    p2 <- indicator_plot(indicators_2017, subpop, indi, measurements[indi][[1]], scale_max[indi][[1]])# + theme(plot.margin = unit(c(0,10,0,10), "pt"))
    print(p2)
    cat("  \n")
  }
}

```
