---
title: "Indicator-State Maximums with Fixed Regional Limits"
output: html_document
---


```{r setup, include=FALSE, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r, include=FALSE, echo=FALSE}
source("setup.R")
library(knitr)
library(patchwork)
library(dplyr)

indicators_12 <- indicators_2012$indicator %>% unique()
subpops_12 <- indicators_2012$subpopulation %>% unique()

indicators_17 <- indicators_2017$indicator %>% unique()
subpops_17 <- indicators_2017$subpopulation %>% unique()

```


```{r fig.height=1, fig.width=15, results='asis', echo=FALSE}

for (indi in indicators_12) {
  for (subpop in region_lookup_table$state_abbr) {
    
    epa_region <-
      region_lookup_table %>%
      filter(state_abbr == subpop) %>%
      pull(epa_region)

    subpop_max <- indicators %>%
      filter(indicator == indi) %>%
      filter(subpopulation == subpop) %>%
      filter(statistic == "95Pct") %>%
      pull(estimate) %>% 
      max()
    
    region_max <- indicators %>%
      filter(indicator == indi) %>%
      filter(subpopulation == epa_region) %>%
      filter(statistic == "95Pct") %>%
      pull(estimate) %>% 
      max()
    
    allsites_max <- indicators %>%
      filter(indicator == indi) %>%
      filter(subpopulation == "All_Sites") %>%
      filter(statistic == "95Pct") %>%
      pull(estimate) %>% 
      max()
    
    across_plot_max <- max(subpop_max, region_max, allsites_max)
    
    if (indi == "PTL" && epa_region == "Region_9") {
      across_plot_max <- min(1000, across_plot_max)
    }
    else if (indi == "CHL" && epa_region == "Region_9") {
      across_plot_max <- min(300, across_plot_max)
    }
    else if (indi == "CHL" && epa_region == "Region_8") {
      across_plot_max <- min(307, across_plot_max)
    }
    else if (indi == "NTL" && epa_region == "Region_9") {
      across_plot_max <- min(5000, across_plot_max)
    }
    else if (indi == "NTL" && epa_region == "Region_7") {
      across_plot_max <- min(6000, across_plot_max)
    }
    
    ### State 2012
    
    df <- indicators_2012 %>% 
      dplyr::filter(subpopulation == subpop,
           indicator == indi,
           statistic %in% bp_stats)
  
    y5 <- getStat(df, "5Pct")
    y95 <- getStat(df, "95Pct")
    
    cat("\n###### ", indi, " | ", subpop, " | 2012 (",y5, ", ", y95, ") \n")
    p1 <- indicator_plot(indicators_2012, subpop, indi, measurements[indi][[1]], across_plot_max)
    print(p1)
    cat("  \n")
    
    ### EPA Region 2012
    
    df <- indicators_2012 %>% 
      dplyr::filter(subpopulation == epa_region,
           indicator == indi,
           statistic %in% bp_stats)
  
    y5 <- getStat(df, "5Pct")
    y95 <- getStat(df, "95Pct")
    
    p2 <- indicator_plot(indicators_2012, epa_region, indi, measurements[indi][[1]], across_plot_max)
    cat("\n###### ", indi, " | ", epa_region, " | 2012 (",y5, ", ", y95, ") \n")
    print(p2)
    cat("  \n")
    
    ### All Sites 2012
    
    df <- indicators_2012 %>% 
      dplyr::filter(subpopulation == "All_Sites",
           indicator == indi,
           statistic %in% bp_stats)
  
    y5 <- getStat(df, "5Pct")
    y95 <- getStat(df, "95Pct")
    
    
    p3 <- indicator_plot(indicators_2012, "All_Sites", indi, measurements[indi][[1]], across_plot_max)
    cat("\n###### ", indi, " | ", "All Sites", " | 2012 (",y5, ", ", y95, ") \n")
    print(p3)
    cat("  \n")
    
    ### State 2017
    
    df <- indicators_2017 %>% 
      dplyr::filter(subpopulation == subpop,
           indicator == indi,
           statistic %in% bp_stats)
  
    y5 <- getStat(df, "5Pct")
    y95 <- getStat(df, "95Pct")
    
    cat("\n###### ", indi, " | ", subpop, " | 2017 (",y5, ", ", y95, ") \n")
    p1 <- indicator_plot(indicators_2017, subpop, indi, measurements[indi][[1]], across_plot_max)
    print(p1)
    cat("  \n")
    
    ### EPA Region 2017
    
    df <- indicators_2017 %>% 
      dplyr::filter(subpopulation == epa_region,
           indicator == indi,
           statistic %in% bp_stats)
  
    y5 <- getStat(df, "5Pct")
    y95 <- getStat(df, "95Pct")
    
    p2 <- indicator_plot(indicators_2017, epa_region, indi, measurements[indi][[1]], across_plot_max)
    cat("\n###### ", indi, " | ", epa_region, " | 2017 (",y5, ", ", y95, ") \n")
    print(p2)
    cat("  \n")

    ### All Sites 2017
    
    df <- indicators_2017 %>% 
      dplyr::filter(subpopulation == "All_Sites",
           indicator == indi,
           statistic %in% bp_stats)
  
    y5 <- getStat(df, "5Pct")
    y95 <- getStat(df, "95Pct")
    
    p3 <- indicator_plot(indicators_2017, "All_Sites", indi, measurements[indi][[1]], across_plot_max)
    cat("\n###### ", indi, " | ", "All Sites", " | 2017 (",y5, ", ", y95, ") \n")
    print(p3)
    
    cat("  \n")
    cat(" --- ")
    cat("  \n")
    
  }
}

```
